name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '*/5 * * * *'
jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: SakivV/SakivV@main
        with:
          feed_list: https://medium.com/feed/@banagevikas'
