name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '00 11 * * *'
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SakivV/blog-post-workflow@main
        with:
          feed_list: https://medium.com/feed/@banagevikas'