name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 0 * * *'
  workflow_dispatch:  
jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SakivV/SakivV@main
        with:
          max_post_count: "3"
          feed_list: https://medium.com/feed/@banagevikas'
